apiVersion: v1
kind: Service
metadata:
  name: microservices-order-services 
spec:
  selector:
    app: microservices-order-services-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer